# This script stores the possibilities of prompts and personalities that will be randomly assigned
# to fit inside of the prompt: 
# f"You are {character}, with {personality} personality. The previous conversation is {prompt}. 
# Now, in one sentence, {question}

questions = [
    "How would you respond?",
    "What's your opinion on this matter?",
    "Can you elaborate on that?",
    "What are your thoughts?",
    "Could you explain further?",
    "What's your perspective?",
    "What are the implications of this?",
    "What's your take on this?",
    "What's your reaction?",
    "What would you recommend?",
    "Can you provide some insights?",
    "How does that make you feel?",
    "What's your interpretation?",
    "What are the consequences?",
    "Do you have any suggestions?",
    "Can you clarify your point?",
    "What's your assessment?",
    "What do you suggest we do?",
    "What's your viewpoint?",
    "How would you analyze this?",
    "How does this affect you?",
    "What's your understanding?",
    "What do you infer from this?",
    "What action would you take?",
    "What's your prediction?",
    "What would you advise?",
    "What do you anticipate?",
    "What's your hypothesis?",
    "How does this relate to you?",
    "What's your diagnosis?",
    "What do you anticipate happening?",
    "What's your insight?",
    "What do you predict will occur?",
    "What do you make of this?",
    "What's your reaction to this?",
    "What would you do differently?",
    "What's your evaluation?",
    "What do you foresee happening?",
    "What's your judgment?",
    "What would you have done?",
    "What's your feeling about this?",
    "What's your recommendation?",
    "What do you predict?",
    "What's your guess?",
    "What's your understanding of this?",
    "What's your take on these events?",
    "What do you suggest we do now?",
    "What do you think will happen next?",
    "What are your feelings about this?",
    "What's your suggestion?",
    "What's your sense of this?",
    "What's your interpretation of this?",
    "What do you think about that?",
    "What do you think will occur?",
    "What do you suggest we do about this?",
    "What's your understanding of the situation?",
    "What would you do in this situation?",
    "What are your thoughts on this matter?",
    "What's your reaction to these events?",
    "What do you think will happen?",
    "What's your perspective on this situation?",
    "What do you think about this?",
    "What do you think we should do next?",
    "What are your impressions?",
    "What do you think we should do?",
    "What do you think is going on here?",
    "What's your opinion about this?",
    "What do you believe should happen?",
    "What do you believe caused this?",
    "What do you think about these developments?",
    "What do you think should be done?",
    "What do you believe will happen next?",
    "What are your feelings on this matter?",
    "What do you think the outcome will be?",
    "What are your thoughts on the matter?",
    "What do you think the solution is?",
    "What do you think about what's been happening?",
    "What's your take on these developments?",
    "What do you believe is the best course of action?",
    "What do you think will be the result?",
    "What are your feelings about what's happening?",
    "What do you think the problem is?",
    "What do you think is causing this?",
    "What do you think we should do about it?",
    "What do you think the reason is?",
    "What's your opinion on these events?",
    "What do you think the solution should be?",
    "What do you think the consequences will be?",
    "What's your reaction to these developments?",
    "What do you think should happen next?",
    "What do you think caused this?",
    "What do you think the outcome will be?",
    "What's your understanding of what's happening?",
    "telling an anecdote about it",
    "sharing a personal experience related to it",
    "providing some interesting facts about it",
    "asking a thought-provoking question about it",
    "expressing enthusiasm for it",
    "expressing skepticism about it",
    "expressing curiosity about it",
    "proposing a solution to a problem related to it",
    "suggesting a different perspective on it",
    "making a joke about it",
    "offering a piece of advice regarding it",
    "expressing concern about it",
    "suggesting a course of action regarding it",
    "expressing excitement about it",
    "expressing disappointment about it",
    "asking for more information about it",
    "sharing an opinion about it",
    "expressing gratitude for it",
    "offering encouragement regarding it",
    "expressing confusion about it",
    "expressing admiration for it",
    "expressing frustration with it",
    "suggesting a change related to it",
    "asking for clarification about it",
    "expressing surprise about it",
    "expressing hope for the future regarding it",
    "expressing regret about it",
    "making a comparison to something else",
    "asking for others' opinions about it",
    "suggesting further exploration of the topic",
    "expressing agreement with a previous point about it",
    "expressing disagreement with a previous point about it",
    "making a prediction about it",
    "sharing a relevant quote or saying about it",
    "offering support for a previous point about it",
    "seeking clarification on a specific aspect of it",
    "bringing up a related topic for discussion",
    "expressing curiosity about a specific detail of it",
    "providing additional context or background information about it",
    "suggesting a different approach to dealing with it",
    "expressing sympathy for those affected by it",
    "raising a concern about potential consequences related to it",
    "expressing confidence in a particular aspect of it",
    "offering a counterargument to a previous point about it",
]

personal_characteristics = [
    "intelligent",
    "mature",
    "humble",
    "wise",
    "sophisticated",
    "empathetic",
    "confident",
    "charismatic",
    "optimistic",
    "adventurous",
    "analytical",
    "creative",
    "courageous",
    "decisive",
    "determined",
    "disciplined",
    "enthusiastic",
    "friendly",
    "generous",
    "genuine",
    "independent",
    "innovative",
    "insightful",
    "kind-hearted",
    "loyal",
    "motivated",
    "open-minded",
    "patient",
    "perseverant",
    "proactive",
    "reliable",
    "resilient",
    "resourceful",
    "sociable",
    "supportive",
    "trustworthy",
    "versatile",
    "visionary",
    "warm-hearted",
    "assertive",
    "authentic",
    "compassionate",
    "cooperative",
    "diligent",
    "diplomatic",
    "flexible",
    "focused",
    "gracious",
    "harmonious",
    "imaginative",
    "inclusive",
    "inspiring",
    "intuitive",
    "knowledgeable",
    "logical",
    "modest",
    "nurturing",
    "objective",
    "organized",
    "patient",
    "perceptive",
    "practical",
    "progressive",
    "rational",
    "reflective",
    "responsible",
    "self-aware",
    "self-disciplined",
    "selfless",
    "sensible",
    "sensitive",
    "serious",
    "sincere",
    "steadfast",
    "tactful",
    "thoughtful",
    "tolerant",
    "unbiased",
    "understanding",
    "versatile",
    "vivacious",
    "wise",
    "witty",
    "charming",
    "capable",
    "composed",
    "considerate",
    "dignified",
    "easygoing",
    "graceful",
    "gregarious",
    "impartial",
    "insightful",
    "methodical",
    "optimistic",
    "pioneering",
    "prudent",
    "rational",
    "receptive",
    "shrewd",
    "tactful",
    "unassuming",
    "arrogant",
    "selfish",
    "stubborn",
    "manipulative",
    "narcissistic",
    "irresponsible",
    "untrustworthy",
    "disrespectful",
    "insensitive",
    "ignorant",
    "inconsiderate",
    "close-minded",
    "impulsive",
    "lazy",
    "indecisive",
    "unreliable",
    "unmotivated",
    "disloyal",
    "incompetent",
    "dishonest",
    "greedy",
    "jealous",
    "volatile",
    "reckless",
    "apathetic",
    "destructive",
    "unethical",
    "insecure",
    "aggressive",
    "passive-aggressive",
    "pessimistic",
    "defensive",
    "self-centered",
    "entitled",
    "intolerant",
    "manipulative",
    "impolite",
    "inflexible",
    "irrational",
    "judgmental",
    "moody",
    "sloppy",
    "disorganized",
    "immature",
    "disruptive",
    "uncooperative"
]